---
- name: Déployer les conteneurs Docker
  hosts: localhost
  become: true

  tasks:
    - name: Créer dossier /home/salma/mon-site-web si absent
      file:
        path: /home/salma/mon-site-web
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Créer dossier /home/salma/cert si absent
      file:
        path: /home/salma/cert
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copier fichiers du site web
      ansible.builtin.synchronize:
        src: "{{ playbook_dir }}/../mon-site-web/"
        dest: "/home/salma/mon-site-web/"
        recursive: yes

    - name: Copier certificats SSL
      ansible.builtin.synchronize:
        src: "{{ playbook_dir }}/../nginx/ssl/"
        dest: "/home/salma/cert/"
        recursive: yes

    - name: Copier fichier de configuration nginx
      copy:
        src: "{{ playbook_dir }}/../nginx/default.conf"
        dest: "/home/salma/nginx.conf"
        owner: root
        group: root
        mode: '0644'

    - name: Créer réseau Docker "app-network"
      community.docker.docker_network:
        name: app-network
        state: present

    - name: Déployer conteneur MySQL
      community.docker.docker_container:
        name: mysql-server
        image: mysql:latest
        state: started
        restart_policy: always
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
        networks:
          - name: app-network
        volumes:
          - "projet-devops_mysql-data:/var/lib/mysql"

    - name: Déployer conteneur phpMyAdmin
      community.docker.docker_container:
        name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        state: started
        restart_policy: always
        ports:
          - "8081:80"
        env:
          PMA_HOST: mysql-server
        networks:
          - name: app-network

    - name: Déployer conteneur Nginx
      community.docker.docker_container:
        name: mon-nginx
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "443:443"
          - "8080:80"
        volumes:
          - "/home/salma/mon-site-web:/usr/share/nginx/html"
          - "/home/salma/cert/cert.pem:/etc/nginx/ssl/cert.pem"
          - "/home/salma/cert/privkey.pem:/etc/nginx/ssl/privkey.pem"
          - "/home/salma/nginx.conf:/etc/nginx/conf.d/default.conf"
        networks:
          - name: app-network


